### ISSUE TITLE
[Bug]: The rich presence does not start automatically with webstorm

### ISSUE THREAD

**Issue by TheDogHusky** [Azn9/JetBrains-Discord-Integration#166]
### What happened?

So I installed Discord-Integration v2 (2.1.2) as the original did not work anymore and wasn't being updated, but I came across an issue:
Every time I start Webstorm (2024.1.5), the rich presence does not start. I'm forced to go in the plugin's settings, and change something to update it, so then the rich presence comes up.

### IDE version

2024.1.5

### Plugin version

2.1.2

### What operating system are you using?

Windows

**Comment by Azn9** [comment]
Hello, thanks for your report. Can you send me on Discord your IDE logs file, please? You can find it by going in the toolbar to Help > Show Log in explorer and it's the idea.log file.

**Comment by TheDogHusky** [comment]
Hey! For now it seems like the issue has been fixed by itself.
I'll try out tomorrow after rebooting to see if it's still there.
