### ISSUE TITLE
[Feature Request]: Option to specify discord app location for WSL integration

### ISSUE THREAD

**Issue by j0rgedev** [Azn9/JetBrains-Discord-Integration#180]
### Describe the feature you'd like

Hello @Azn9, thank you so much for your hard work on this project! I was wondering if it might be possible to add an option to choose the Discord app from a specific folder. I'm using JetBrains IDEs within WSL, and Discord is installed on my Windows system rather than in WSL. To get the plugin working properly, it would be really helpful if I could point it to the Discord app installed on Windows.

**Comment by Azn9** [comment]
Hello @j0rgedev ! Thanks for your message I appreciate it ❤️

Unfortunately, this is not possible, as WSL apps cannot access the host. I know that you can access your drives but discord listens to a specific file that cannot be found. 
You could however use something like https://github.com/jstarks/npiperelay to mount the `\\.\pipe\discord-ipc-0` file to `/run/user/{userid}/discord-ipc-0`, this \*should\* in theory work.

This is however not something that I will (or at least could) implement in the plugin, you'll have to rely on third-party software.

**Comment by j0rgedev** [comment]
Thank you so much for answering. I understand and will try installing npiperelay. Keep up the good work!
