### ISSUE TITLE
[Bug]: Plugin thinks, Rich Presence is not enabled, but it is.

### ISSUE THREAD

**Issue by scaui0** [Azn9/JetBrains-Discord-Integration#189]
### What happened?

![grafik](https://github.com/user-attachments/assets/2431f6fb-284a-40c3-af91-2aa759e9ccdc)
In dicord, the activity has not changed.

### IDE version

2024.2

### Plugin version

2.1.3

### What operating system are you using?

Windows

**Comment by Azn9** [comment]
This error means the plugin detects a running discord client without an IPC file. This can be caused if you launched Discord as administrator, for instance, or if you're using a custom Discord client that is not working as the original one.

**Comment by scaui0** [comment]
I didn't start Discord as an administrator and I'm using the original client. When I start discord an administrator I get a message in PyCharm.
![grafik](https://github.com/user-attachments/assets/0e37f9b7-be9b-45c2-b0f1-0832f39f9e4d)

**Comment by scaui0** [comment]
After restarting PyCharm and Discord it worked. I don't know why, but is does.

**Comment by Azn9** [comment]
Can you run the following command in a CMD and give me the output?
`FOR %I IN (0,1,2,3,4,5,6,7,8,9) DO (IF EXIST "\\?\pipe\discord-ipc-%I" (echo IPC %I found) ELSE (echo IPC %I not found))`

**Comment by Azn9** [comment]
> After restarting PyCharm and Discord it worked. I don't know why, but is does.

Strange, I don't think that this could be an issue with the plugin, as it tries to reconnect every 5s, so it might be more a Discord-related issue 🤔

**Comment by scaui0** [comment]
C:\Users\USER>FOR %I IN (0,1,2,3,4,5,6,7,8,9) DO (IF EXIST "\\?\pipe\discord-ipc-%I" (echo IPC %I found) ELSE (echo IPC %I not found))

C:\Users\USER>(IF EXIST "\\?\pipe\discord-ipc-0" (echo IPC 0 found )  ELSE (echo IPC 0 not found ) )
IPC 0 found

C:\Users\USER>(IF EXIST "\\?\pipe\discord-ipc-1" (echo IPC 1 found )  ELSE (echo IPC 1 not found ) )
IPC 1 not found

C:\Users\USER>(IF EXIST "\\?\pipe\discord-ipc-2" (echo IPC 2 found )  ELSE (echo IPC 2 not found ) )
IPC 2 not found

C:\Users\USER>(IF EXIST "\\?\pipe\discord-ipc-3" (echo IPC 3 found )  ELSE (echo IPC 3 not found ) )
IPC 3 not found

C:\Users\USER>(IF EXIST "\\?\pipe\discord-ipc-4" (echo IPC 4 found )  ELSE (echo IPC 4 not found ) )
IPC 4 not found

C:\Users\USER>(IF EXIST "\\?\pipe\discord-ipc-5" (echo IPC 5 found )  ELSE (echo IPC 5 not found ) )
IPC 5 not found

C:\Users\USER>(IF EXIST "\\?\pipe\discord-ipc-6" (echo IPC 6 found )  ELSE (echo IPC 6 not found ) )
IPC 6 not found

C:\Users\USER>(IF EXIST "\\?\pipe\discord-ipc-7" (echo IPC 7 found )  ELSE (echo IPC 7 not found ) )
IPC 7 not found

C:\Users\USER>(IF EXIST "\\?\pipe\discord-ipc-8" (echo IPC 8 found )  ELSE (echo IPC 8 not found ) )
IPC 8 not found

C:\Users\USER>(IF EXIST "\\?\pipe\discord-ipc-9" (echo IPC 9 found )  ELSE (echo IPC 9 not found ) )
IPC 9 not found

Thank you for your efforts! 😄

**Comment by Azn9** [comment]
So yes, an IPC file is detected, but the plugin cannot connect to it. There is nothing more I could do about that; it's not an error with the plugin, unfortunately :/
I'm glad a restart fixes it, but it's not optimal.

> Thank you for your efforts! 😄

You're welcome!
