### ISSUE TITLE
[Bug]: `Application name` settings doesn't change anything

### ISSUE THREAD

**Issue by Kyrela** [Azn9/JetBrains-Discord-Integration#192]
## To reproduce

1. Open PyCharm Professional
2. Go to `File` > `Settings` > `Other Settings` > `Discord`
3. Change the `Application name` dropdown value to `JetBains IDE`
4. Click on `OK`
5. Close the IDE
6. Open Discord
7. Open the IDE

## Expected behavior
In Discord, the Rich Presence title should display `JetBains IDE`

## Actual behavior
In Discord, the Rich Presence title displays `PyCharm Professional`

*Note: this also applies to the `IDE Name` value of the `Application name` dropdown*

### IDE version

PyCharm 2024.2.1 (Professional Edition) Build #PY-242.21829.153, built on August 29, 2024 Licensed to **REDACTED** Subscription is active until October 5, 2024. For educational use only. Runtime version: 21.0.3+13-b509.11 amd64 (JCEF 122.1.9) VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. Toolkit: sun.awt.windows.WToolkit Windows 11.0 GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation Memory: 1956M Cores: 16 Registry:   ide.experimental.ui=true   i18n.locale=   terminal.new.ui=true Non-Bundled Plugins:   com.nasller.CodeGlancePro (1.9.0)   intellij.webp (242.20224.155)   com.jetbrains.space (242.21829.142)   name.kropp.intellij.makefile (242.20224.155)   com.intellij.plugin.adernov.powershell (2.7.0)   com.github.camork.fileExpander (2.5)   ru.adelf.idea.dotenv (2024.2.1)   dev.azn9.plugins.discord (2.1.3.242)   com.github.copilot (1.5.20.6554)   zielu.gittoolbox (500.2.15+242)   com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.16.1)

### Plugin version

2.1.3

### What operating system are you using?

Windows

**Comment by Azn9** [comment]
Note for myself: the icon is updated, but not the name
