### ISSUE TITLE
[Bug]: Buttons not showing

### ISSUE THREAD

**Issue by Xyndra** [Azn9/JetBrains-Discord-Integration#193]
### What happened?

![image](https://github.com/user-attachments/assets/81fbd845-9fad-4b74-9018-f1bb02c2d26a)
![image](https://github.com/user-attachments/assets/c1cc60f4-aea5-4206-bc5d-fe50e7651a48)

### IDE version

IntelliJ IDEA 2024.2.1 (Ultimate Edition) Build #IU-242.21829.142

### Plugin version

2.1.3

### What operating system are you using?

Windows

### Relevant log output

```shell
None
```

**Comment by Azn9** [comment]
You cannot see your "own" buttons :(
Use another account to be sure that this is not working

**Comment by Xyndra** [comment]
oh, sorry for the issue then

**Comment by Azn9** [comment]
No worries! That's the fastest issue I've ever solved I think :joy:

**Comment by Azn9** [comment]
But feel free to reopen it if it is actually broken!
