### ISSUE TITLE
[Bug]: Presence not showing up as expected.

### ISSUE THREAD

**Issue by newtox** [Azn9/JetBrains-Discord-Integration#209]
### What happened?

It doesn't work then Discord is being used in the browser.

### IDE version

PhpStorm 2024.1.4

### Plugin version

2.1.3

### What operating system are you using?

Windows

**Comment by Azn9** [comment]
This won't work, browser clients don't have an IPC connection. Use https://arrpc.openasar.dev/ for it to work.

**Comment by newtox** [comment]
So if I understand that correctly, I can clone the repository on my ubuntu server, then just run the js file and can establish a connection via the ip and then over to discord?
