### ISSUE TITLE
[Bug]: Plugin detects false errors when starting the IDE.

### ISSUE THREAD

**Issue by henry0337** [Azn9/JetBrains-Discord-Integration#218]
### What happened?

i always got this notification whenever booting up IDE, even i'm not logging into the browser:
"**Discord detected in a web browser, this will prevent the plugin from connecting to Discord!**"

### IDE version

IntelliJ IDEA Community 2024.2.4

### Plugin version

2.1.4

### What operating system are you using?

Windows

**Comment by Azn9** [comment]
Note for me: this line is missing `contains("discord")` https://github.com/Azn9/JetBrains-Discord-Integration/blob/140869ffe5d0cc4b54c6d99e22cefdf9b2ab7dfa/plugin/common/src/main/kotlin/dev/azn9/plugins/discord/diagnose/DiagnoseService.kt#L152

**Comment by MeridianGH** [comment]
+1, I tried logging out of my Discord browser instance and the warning was still there
