### ISSUE TITLE
[Bug]: Light mode settings section in dark mode IDE

### ISSUE THREAD

**Issue by avi12** [Azn9/JetBrains-Discord-Integration#223]
### What happened?

![image](https://github.com/user-attachments/assets/302974e2-a0a3-4ba6-a25e-0571c62a69ae)

### IDE version

WebStorm 2024.2.4

### Plugin version

2.1.4

### What operating system are you using?

Windows

**Comment by Azn9** [comment]
The plugins does not specify any color in the UI, it uses your theme. This is not an issue caused by the plugin.

**Comment by avi12** [comment]
IDK how plugin development works, but I do know that some plugins get it right
![image](https://github.com/user-attachments/assets/4a1b93fb-68c6-44d4-92ab-c4914b371843)

**Comment by Azn9** [comment]
> IDK how plugin development works, but I do know that some plugins get it right

That is not something I manage, I just tell the IDE which layout to display (i.e. where should the elements be), not what the elements look. Then the IDE builds the UI itself, I don't change anything.

**Comment by Azn9** [comment]
There is most likely an issue with your theme, not this plugin.

**Comment by avi12** [comment]
The theme is the High Contrast theme provided by JetBrains
![image](https://github.com/user-attachments/assets/51777a97-82a2-47ce-8123-9893d7a89c0e)
