### ISSUE TITLE
Allows the use of the project icon in the rich presence

### ISSUE THREAD

**Issue by Azn9** [Azn9/JetBrains-Discord-Integration#28]
https://github.com/Almighty-Alpaca/JetBrains-Discord-Integration/issues/85

The icons displayed can also be sent by the rpc and no longer statically uploaded to the dev portal, so this is now possible

**Comment by Azn9** [comment]
WIP in https://github.com/Azn9/JetBrains-Discord-Integration/tree/feat/use-project-icon

**Comment by Azn9** [comment]
Unfortunately, Discord does not allow the use of base64-encoded images, so this is finally not possible :'(

**Comment by KarstenPH** [comment]
just in case anyone wants a workaround (for future reference): set your large icon to `Custom`, put in `/src/$ProjectName.png` (or choose your file format of choice (assuming it's supported)) as the source, then put in the logo of your app on the /src/ directory
(technically you could put it in any folder inside /src/ too if you wish but you'll need to adjust the directory accordingly and you need to make sure that all of your projects follow the same asset folder structure)

I wish there was an option to perhaps have the ability to choose a "fallback icon" option in case that there was no file found and an "override" option that is project-specific but that's out of this enhancement's scope

**Comment by Azn9** [comment]
@KarstenPH 

> just in case anyone wants a workaround (for future reference): set your large icon to `Custom`, put in `/src/$ProjectName.png` (or choose your file format of choice (assuming it's supported)) as the source, then put in the logo of your app on the /src/ directory (technically you could put it in any folder inside /src/ too if you wish but you'll need to adjust the directory accordingly and you need to make sure that all of your projects follow the same asset folder structure)

This won't work, discord expect either an asset id, or a valid url (which `/src/something.png` is not). You can however add your project's github direct path, like `https://github.com/Azn9/JetBrains-Discord-Integration/blob/develop/.idea/icon.png?raw=true` for this project for instance).


> I wish there was an option to perhaps have the ability to choose a "fallback icon" option in case that there was no file found and an "override" option that is project-specific but that's out of this enhancement's scope

Yeah that is planned in https://github.com/Azn9/JetBrains-Discord-Integration/issues/232
