### ISSUE TITLE
Incorrect language icon displayed on Discord

### ISSUE THREAD

**Issue by npxtune** [Azn9/JetBrains-Discord-Integration#41]
# What is the issue?
Selecting the Flat or Atom language icons results in the usage of the Material one instead. e.g:

### Expected outcome:
![Screenshot 2023-11-17 at 14 17 11](https://github.com/Azn9/JetBrains-Discord-Integration/assets/42376598/eda56fb4-e8ba-4e3f-bb2a-409889564274)

### What actually happens:
![Screenshot 2023-11-17 at 14 17 19](https://github.com/Azn9/JetBrains-Discord-Integration/assets/42376598/ae851295-7cf2-477b-bb3d-38077a68e03c)
(This is the icon for the Material Language icon themes)

---
A fix would be appreciated :)

Cheers

**Comment by Azn9** [comment]
Resolved by https://github.com/Azn9/JetBrains-Discord-Integration/commit/8dab8da05778aefc37cf0b7fb4aa4da541cecd24

**Comment by npxtune** [comment]
Seems to work now, however I have to manually change the icon theme in the project's discord xml file because the editor does not override / update the file's value.

**Comment by Azn9** [comment]
You can set the theme to "default" in the project options ;)
