### ISSUE TITLE
Exception when browsing files

### ISSUE THREAD

**Issue by thegatesdev** [Azn9/JetBrains-Discord-Integration#74]
Hello there!

When clicking on a file in my IntelliJ IDEA file browser, the plugin produces this exception:
```
java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:381)
	at java.desktop/java.awt.Desktop.browse(Desktop.java:531)
	at dev.azn9.plugins.discord.settings.options.types.TemplateOption.textFieldInfoExtension$lambda-0(TemplateOption.kt:45)
```

I'm running an Arch Linux system with IntelliJ installed from the official pacman repository.

Below is the full stacktrace:
[intellij-err.txt](https://github.com/Azn9/JetBrains-Discord-Integration/files/13997610/intellij-err.txt)

I must add that the plugin correctly works when not having any files open, the integration shows in Discord with the project name and time elapsed.

**Comment by thegatesdev** [comment]
It seems it is working now without changing anything, and it is detecting the files correctly without exceptions.
This is probably only an issue when first installing the plugin.

**Comment by Azn9** [comment]
Thanks for the report! Even if this only happens the first time it is annoying. I'll take a look at it in the next few days.
