### ISSUE TITLE
Change plugin ID to avoid conflicts with the original plugin

### ISSUE THREAD

**Issue by Azn9** [Azn9/JetBrains-Discord-Integration#8]
As the plugin ID is the same, some information displayed on the plugin are outdated

![image](https://github.com/Azn9/JetBrains-Discord-Integration/assets/22526783/898e3a2c-2b8b-4d2a-a9bf-17b1403ffb13)

**Comment by net-tech** [comment]
Hi, is this still being worked on?

**Comment by Azn9** [comment]
> Hi, is this still being worked on?

It is still planned however not before the next update. I was discussing with AlmightyAlpaca, the owner of the original plugin to merge this fork onto the main plugin and only focus on contributing to the main repo instead of maintaining this fork so I delayed this feature. Nevertheless, it is still uncertain so this is on hold until I choose to do it or not.
