### ISSUE TITLE
[Bug]: False positive with arRPC

### ISSUE THREAD

**Issue by UwUDev** [Azn9/JetBrains-Discord-Integration#81]
### What happened?

The plugin thinks I'm in a browser and that Rich Presence doesn't work, but it does.

![image](https://github.com/Azn9/JetBrains-Discord-Integration/assets/61664271/42e8de2e-6f74-4880-9e6e-37909a432459)
![image](https://github.com/Azn9/JetBrains-Discord-Integration/assets/61664271/189b91f9-391d-4f89-a544-1834df394eaa)

### IDE version

RustRover 2023.3 EAP

### Plugin version

2.0.8

### What operating system are you using?

Windows

**Comment by Azn9** [comment]
Thanks for the report I'll have a look at that!

**Comment by Azn9** [comment]
Fixed with https://github.com/Azn9/JetBrains-Discord-Integration/commit/fa8017d65de02c249a8c457677fd4a2a19f38761. I will close this issue once it has been merged and released.
