### ISSUE TITLE
[Bug]: Changing the icon theme doesn't do anything

### ISSUE THREAD

**Issue by lynn2910** [Azn9/JetBrains-Discord-Integration#85]
### What happened?

At the installation, i saw this default icon:
![image](https://github.com/Azn9/JetBrains-Discord-Integration/assets/73949405/0efd1c6d-6609-4d78-9a1a-e772ab067061)

And wanted to change the theme.
But changing to Atom, Material or Flat doesn't change anything, even if i restart the IDE.

Here is the icon with the theme "flat": 
![image](https://github.com/Azn9/JetBrains-Discord-Integration/assets/73949405/0c41e381-962b-442e-817f-83b6013ddb4d)

### IDE version

RustRover 2023.3 EAP (233.14015.152)

### Plugin version

2.0.8

### What operating system are you using?

Linux

**Comment by lynn2910** [comment]
And if I disable the rich presence in the settings, it simply vanish and don't work when i activate it back

**Comment by Azn9** [comment]
I am able to change theme via the settings. Please make sure that you're changing it on the "Project" options or that you have selected "Default" on the project.

Material:
![image](https://github.com/Azn9/JetBrains-Discord-Integration/assets/22526783/cc64f88c-a06e-4419-a1ca-49c00f798a3f)

Atom:
![image](https://github.com/Azn9/JetBrains-Discord-Integration/assets/22526783/50c37b07-ef2f-49fc-99ee-9eb5cf27a56c)

There is an issue tho, but I'll track it on #86.
